# Generated by Django 4.2.23 on 2025-07-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanitationcheck',
            name='temperature',
            field=models.DecimalField(decimal_places=1, default=36.0, max_digits=4, verbose_name='体温'),
        ),
    ]
