# Generated by Django 5.0.7 on 2025-08-25 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0002_alter_sanitationcheck_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('management_pin', models.CharField(blank=True, max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AddField(
            model_name='employee',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hygiene.office'),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('work_start_time', models.TimeField(blank=True, null=True)),
                ('work_end_time', models.TimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='hygiene.employee')),
            ],
            options={
                'unique_together': {('date', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='RecordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('temperature', 'temperature'), ('no_health_issues', 'no_health_issues'), ('family_no_symptoms', 'family_no_symptoms'), ('no_respiratory_symptoms', 'no_respiratory_symptoms'), ('no_severe_hand_damage', 'no_severe_hand_damage'), ('no_mild_hand_damage', 'no_mild_hand_damage'), ('nails_groomed', 'nails_groomed'), ('proper_uniform', 'proper_uniform'), ('no_work_illness', 'no_work_illness'), ('proper_handwashing', 'proper_handwashing')], max_length=40)),
                ('is_normal', models.BooleanField(default=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hygiene.record')),
            ],
            options={
                'unique_together': {('record', 'category')},
            },
        ),
        migrations.CreateModel(
            name='SupervisorConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hygiene.employee')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_confirmation', to='hygiene.record')),
            ],
        ),
        migrations.DeleteModel(
            name='SanitationCheck',
        ),
    ]
