# Generated by Django 5.0.7 on 2025-08-28 08:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0003_office_remove_employee_department_employee_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-date', 'employee_id']},
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='recorditem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='個人コード（例：6桁）。後で null=False に締めます。', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', message='数字6桁で入力してください。')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='office',
            field=models.ForeignKey(help_text='所属営業所。null不可。', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hygiene.office'),
        ),
        migrations.AlterField(
            model_name='office',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='営業所コード（例：KM3076）。後で null=False に締めます。', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2}\\d{4}$', message='英字2文字+数字4桁（例：KM3076）で入力してください。')]),
        ),
        migrations.AlterField(
            model_name='office',
            name='management_pin',
            field=models.CharField(blank=True, help_text='管理者用PIN（開発用）。未設定可。', max_length=4, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', message='数字4桁で入力してください。')]),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['code'], name='emp_code_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['office', 'name'], name='emp_office_name_idx'),
        ),
        migrations.AddIndex(
            model_name='office',
            index=models.Index(fields=['code'], name='office_code_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['date'], name='record_date_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['employee', 'date'], name='record_emp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='recorditem',
            index=models.Index(fields=['record'], name='item_record_idx'),
        ),
        migrations.AddIndex(
            model_name='recorditem',
            index=models.Index(fields=['category'], name='item_category_idx'),
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('date', 'employee'), name='uniq_record_per_day_employee'),
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.CheckConstraint(check=models.Q(('work_end_time__isnull', True), ('work_start_time__isnull', True), ('work_start_time__lte', models.F('work_end_time')), _connector='OR'), name='work_start_lte_end_or_null'),
        ),
        migrations.AddConstraint(
            model_name='recorditem',
            constraint=models.UniqueConstraint(fields=('record', 'category'), name='uniq_item_per_record_category'),
        ),
    ]
