# Generated by Django 5.0.7 on 2025-08-29 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0004_alter_record_options_alter_record_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_records', to='hygiene.employee'),
        ),
    ]
