# Generated by Django 5.0.7 on 2025-08-29 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0005_record_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='supervisor',
            new_name='supervisor_selected',
        ),
    ]
