# Generated by Django 5.0.7 on 2025-10-11 14:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0008_record_value_text_and_work_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='status',
        ),
        migrations.RemoveField(
            model_name='record',
            name='status_jp',
        ),
        migrations.AlterField(
            model_name='employee',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='個人コード（6桁想定）。', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{6}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hygiene.office'),
        ),
        migrations.AlterField(
            model_name='office',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='営業所コード（例：KM3076）。', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2}\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='office',
            name='management_pin',
            field=models.CharField(blank=True, help_text='管理者用PIN（開発用）。未設定可。', max_length=4, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='recorditem',
            name='category',
            field=models.CharField(choices=[('temperature', 'temperature'), ('no_health_issues', 'no_health_issues'), ('family_no_symptoms', 'family_no_symptoms'), ('no_respiratory_symptoms', 'no_respiratory_symptoms'), ('no_severe_hand_damage', 'no_severe_hand_damage'), ('no_mild_hand_damage', 'no_mild_hand_damage'), ('nails_groomed', 'nails_groomed'), ('proper_uniform', 'proper_uniform'), ('no_work_illness', 'no_work_illness'), ('proper_handwashing', 'proper_handwashing'), ('work_type', 'work_type')], max_length=40),
        ),
    ]
