# Generated by Django 5.0.7 on 2025-10-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0009_remove_record_status_remove_record_status_jp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('general', '一般'), ('deputy_manager', '副所長'), ('branch_admin', '所長'), ('manager', '本部')], db_index=True, default='general', help_text='役職コード（general / deputy_manager / branch_admin / manager）', max_length=32),
        ),
        migrations.AlterField(
            model_name='recorditem',
            name='value_text',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['office', 'position'], name='emp_office_position_idx'),
        ),
    ]
